title: Site

sections:
  navpages:
    headline: Main Pages (Navigation)
    type: pages
    layout: list
    status: listed
    image: false
  
  subpages:
    headline: Subpages
    type: pages
    layout: list
    status: unlisted
    image: false
    

